name: Ihor Solodrai
bio: 'Software Engineer from Kyiv, Ukraine'
description: A personal page
external-image: false
picture: assets/images/profile.jpg
resume: false 
resume-external: true
resume-url: 'https://google.com/?q=my+resume'
url: 'https://koppl.in/indigo'
permalink: '/:title/'
disqus:
  shortname: mydisqus
  categories:
    - blog
    - project
github: theihor
email: ihor.solodrai@gmail.com
authors:
  theihor:
    name: Ihor Solodrai
    bio: 'Software Engineer from Kyiv, Ukraine'
    external-image: false
    picture: assets/images/profile.jpg
width: normal
projects: false
about: true 
blog: false 
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: false
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji
#  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  - travis.sh
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
